# Generated by Django 3.0.8 on 2020-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('tech', models.CharField(choices=[('WordPress', 'WordPress'), ('Woocommerce', 'Wocommerce'), ('Majento', 'Majento')], max_length=200)),
                ('traffic', models.PositiveIntegerField()),
                ('country', models.CharField(blank=True, max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
